/**
 * GlassVault - Shared Types
 *
 * Central type definitions shared between the frontend (apps/web)
 * and the backend agent (apps/api).
 */

// ---------------------------------------------------------------------------
// Chain Configuration
// ---------------------------------------------------------------------------

export type SupportedChainId = 84532 | 10143;

export interface ChainConfig {
  id: SupportedChainId;
  name: string;
  rpcUrl: string;
  blockExplorerUrl: string;
  nativeCurrency: {
    name: string;
    symbol: string;
    decimals: number;
  };
  /** USDC contract address on this chain (if available) */
  usdcAddress?: string;
}

// ---------------------------------------------------------------------------
// Agent Intent Schema
// ---------------------------------------------------------------------------

export type AgentAction =
  | "transfer"
  | "swap"
  | "lp_deposit"
  | "portfolio_report"
  | "revoke_permissions";

export interface AgentIntent {
  action: AgentAction;
  chainId: SupportedChainId;
  /** Token to send or swap from */
  fromToken?: string;
  /** Token to receive (swap only) */
  toToken?: string;
  /** Amount in human-readable units (e.g. "0.01") */
  amount?: string;
  /** Destination wallet address (transfer only) */
  recipient?: string;
  /** Slippage tolerance in basis points (swap/lp only, e.g. 50 = 0.5%) */
  slippageBps?: number;
  /** Natural language summary of the user's request */
  rawIntent: string;
  /** Venice AI confidence score (0-1) */
  confidence: number;
}

// ---------------------------------------------------------------------------
// Transaction Status
// ---------------------------------------------------------------------------

export type TxStatus =
  | "pending"
  | "submitted"
  | "confirmed"
  | "failed"
  | "reverted";

export interface TxStatusUpdate {
  taskId: string;
  status: TxStatus;
  txHash?: string;
  chainId: SupportedChainId;
  action: AgentAction;
  timestamp: number;
  /** Error message if status is failed or reverted */
  errorMessage?: string;
  /** Gas fee paid in USDC (human-readable) */
  gasFeeUsdc?: string;
}

// ---------------------------------------------------------------------------
// Permission Grant
// ---------------------------------------------------------------------------

export interface PermissionGrant {
  id: string;
  grantedAt: number;
  expiresAt?: number;
  chainId: SupportedChainId;
  spendCapUsdc: string;
  delegateeAddress: string;
  actions: AgentAction[];
  /** ERC-7715 permission context returned by MetaMask */
  permissionContext: string;
}

// ---------------------------------------------------------------------------
// Agent Execution Request / Response
// ---------------------------------------------------------------------------

export interface AgentExecuteRequest {
  intent: AgentIntent;
  /** ERC-7715 delegation context from the user's MetaMask approval */
  permissionContext: string;
  /** Webhook URL for 1Shot status callbacks */
  webhookUrl: string;
}

export interface AgentExecuteResponse {
  success: boolean;
  taskId?: string;
  errorMessage?: string;
}

// ---------------------------------------------------------------------------
// Venice AI Receipt
// ---------------------------------------------------------------------------

export interface TxReceipt {
  taskId: string;
  action: AgentAction;
  chainId: SupportedChainId;
  summary: string;
  txHash: string;
  gasFeeUsdc: string;
  /** Base64-encoded PNG receipt image generated by Venice AI */
  receiptImageBase64?: string;
  timestamp: number;
}
